services:
  # Servicio del Backend (Node.js/Express)
  - type: web
    name: parfum-shop-backend
    env: node
    # ¡Importante! Asegúrate de que la ruta sea correcta
    rootDir: server 
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MERCADOPAGO_ACCESS_TOKEN
        fromSecret: true # Para que lo ingreses en el dashboard de Render
      - key: EMAIL_USER
        fromSecret: true
      - key: EMAIL_PASS
        fromSecret: true
      - key: EMAIL_TO
        fromSecret: true

  # Servicio del Frontend (React Static Site)
  - type: web
    name: parfum-shop-frontend
    env: static
    # ¡Importante! Asegúrate de que la ruta sea correcta
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    # Regla de reescritura para que React Router funcione
    routes:
      - type: rewrite
        source: /*
        destination: /index.html